name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build-DB
      run: docker-compose build
    
    - name: Create-DB
      run: docker-compose up -d

    - name: Wait for PostgreSQL
      run: |
        while ! nc -z localhost 5432; do   
          sleep 1
        done
    
    - name: Wait for DB to be ready
      run: sleep 10

    - name: Test
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
    
    - name: Build
      run: go build -o program ./...

    - name: List build files
      run: ls -la

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: program
        path: ./program

  docker: 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.6.1

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.LOGIN_DOCKER_HUB }}
        password: ${{ secrets.SENHA_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: borgesmath/go_ci:${{github.ref_name}} # nome tem que ser em minusculas, nome da branch em seguida

