name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build-DB
      run: docker-compose build
    
    - name: Create-DB
      run: docker-compose up -d

    # Novo passo para esperar o PostgreSQL estar pronto
    - name: Wait for PostgreSQL
      run: |
        while ! nc -z localhost 5432; do   
          sleep 1
        done
    
    - name: Wait for DB to be ready
      run: sleep 10

    - name: Test
      run: go test -v ./...

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
    - name: Build
      run: go build -v ./...

  docker: 
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
